
<div class="alert alert-danger">
    <h2 class="alert-heading">404 Not Found</h2>
    <p class="alert-body">
        Requested URL <code><?=htmlspecialchars( $_SERVER["HTTP_HOST"] ), htmlspecialchars( $_SERVER["REQUEST_URI"] ) ?></code> can not be transformed into a response by this server.
    </p>
</div>

<dl class="row">
    <dt class="col-sm-2">IP:</dt>
    <dd class="col-sm-10"><?=htmlspecialchars($_SERVER["REMOTE_ADDR"])?></dd>
    <dt class="col-sm-2">Agent:</dt>
    <dd class="col-sm-10"><?=htmlspecialchars($_SERVER["HTTP_USER_AGENT"])?></dd>
</dl>