<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title Home
 * @description Here goes your web application
 * @require Application
 *
 * @var DefaultRenderContext $this
 */

?>
<div class="content">
    <h3>Home</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet architecto blanditiis deserunt earum fugit id inventore itaque maxime necessitatibus nihil, nulla possimus quaerat quasi quos rerum saepe soluta sunt voluptate.
    </p>
</div>
