<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title Home
 * @description Hello, world!
 * @require Application
 *
 * @var DefaultRenderContext $this
 */

?>
<style type="text/css">
	#my-header {
		display: none;
	}
</style>
<div class="content">
	<div class="jumbotron">
		<h1 class="display-4">Welcome!</h1>
		<p class="lead">
			This is a Skyline CMS template using the bootstrap css framework.<br>
			We'll invite you to modify it into your own application!
		</p>
		<p class="lead">
			<strong>Have Fun!</strong>
		</p>
		<hr class="my-4">
		<p>
			See here some explanations to start right away!
		</p>
		<p class="lead">
			<a class="btn btn-primary btn" href="#" role="button">The Skyline Structure</a>
		</p>
	</div>
</div>
