<?php

use Skyline\Render\Context\DefaultRenderContext;
/**
 * @title Home
 * @description Here goes your web application
 * @require Application
 *
 * @var DefaultRenderContext $this
 */

?>
<div class="content">
    <h3>Submenu 1</h3>
    <p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium, architecto asperiores eaque est fuga iure laborum molestiae nobis non nostrum quas recusandae sapiente tempora ullam voluptatibus? Impedit nam sapiente similique!
    </p>
</div>
